# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Away"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
  JSON:
    allow_blessed: '1'
    convert_blessed: '1'

plugins:
    DBIC:
        away: 
            dsn: "dbi:SQLite:dbname=./data/away.db"
            options:
                sqlite_unicode: 1

leave_categories:
  - "Vacation"
  - "Meeting/Seminar/Conference"
  - "20% time"
  - "Other"

year_begins:
    - 10
    - 1

extra_hols:
    -
        - 2011
        - 04
        - 29

